[package]
name = "cita-contracts"
version = "1.0.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
rocksdb = "0.12.2"
cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
