# docker run -v $PWD/..:/sources -v $PWD/binaries:/binaries cita/build
FROM ubuntu:17.04

RUN apt-get update											     							\
	&& apt-get --assume-yes install build-essential curl file sudo  git capnproto			\
	   	   						libsnappy-dev libgoogle-perftools-dev libunwind8-dev        \
								libssl-dev rabbitmq-server libudev-dev			   			\
	&& apt-get purge -y --auto-remove   													\
 	&& rm -rf /var/lib/apt/lists /tmp/*

RUN curl -s https://static.rust-lang.org/rustup.sh | sh -s -- --channel=nightly				\
	&& rm  -rf /tmp/*
RUN useradd -m cita																			\
	&& echo 'cita ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/cita 																			\

ENV PATH $PATH:/root/.cargo/bin:/sources/bin
WORKDIR /sources
# CMD make setup \
# 	&& make release
