[package]
name = "transaction"
version = "0.6.0"
authors = ["u2 <zhangyaning1985@gmail.com>"]

[dependencies]
sha3 = { path = "../sha3"}
util = { path = "../util"}
cita-ed25519 = { path = "../ed25519" }
libproto = { path = "../proto" }
rustc-serialize = "0.3"
protobuf = { version = "^1.0.0"}
log = "0.3"
env_logger = "0.3"

[dev-dependencies]
uuid = { version = "0.4", features = ["v4"] }
