[package]
name = "tx_pool"
version = "0.6.0"
authors = ["rink1969 <rink1969@cryptape.com>"]

[dependencies]
lru-cache = "0.1"
libproto = { path = "../proto" }
util = { path = "../util" }
cita-ed25519 = { path = "../ed25519" }