#!/bin/bash
# 1) source env.sh
# 2) cita --setup
# 3) cita --start
# 4) cita --status|--chain|--consensus
# 5) cita --stop
bins="network chain consensus_tendermint jsonrpc"
log_dir="$(dirname $0)/log"
data_dir="$(dirname $0)/data"

function cita_setup() {
    mkdir -p ${log_dir}

    node=node$1
    echo "setup ${node}"

    # rabbitmq
    /etc/init.d/rabbitmq-server restart
    rabbitmqctl add_vhost ${node}
    rabbitmqctl set_permissions -p ${node} guest ".*" ".*" ".*"
    rabbitmqctl list_permissions -p ${node}
}

function cita_start() {
    node=node$1
    if [ ! -n "$2" ]; then
        echo "starting ${node}"
        nohup bin/network			    -c network.toml	     >${log_dir}/${node}.network    2>&1 &
        echo $! >> .pid
        nohup bin/consensus_tendermint	-c consensus.json	 >${log_dir}/${node}.consensus  2>&1 &
        echo $! >> .pid
        nohup bin/jsonrpc               -c jsonrpc.json	     >${log_dir}/${node}.jsonrpc    2>&1 &
        echo $! >> .pid
        nohup bin/chain					-c genesis.json		 >${log_dir}/${node}.chain	    2>&1 &
        echo $! >> .pid
    else
        echo "starting ${node} debug"
        RUST_LOG= nohup bin/network -c network.toml	     >${log_dir}/${node}.network    2>&1 &
        echo $! >> .pid
        RUST_LOG=consensus_tendermint nohup bin/consensus_tendermint	-c consensus.json	 >${log_dir}/${node}.consensus  2>&1 &
        echo $! >> .pid
        RUST_LOG=jsonrpc,jsonrpc_types,transaction=trace nohup bin/jsonrpc -c jsonrpc.json	 >${log_dir}/${node}.jsonrpc    2>&1 &
        echo $! >> .pid
        RUST_LOG=chain,core,transaction=trace nohup bin/chain	-c genesis.json		 >${log_dir}/${node}.chain	    2>&1 &
        echo $! >> .pid
    fi
    cita_status $1
}

function cita_stop(){
    for pid in $(cat .pid)
    do
        kill -9 ${pid}
    done
    rm -f .pid
    touch .pid
    cita_status $1
}

function cita_restart() {
	cita_stop $1
	cita_setup $1
	cita_start $1
}

function cita_status(){
    for pid in $(cat .pid)
    do
        ps -A -o command:50,pid,time|grep ${pid} |grep -v "grep"
    done
}

function cita_chain() {
    node=node$1
	tail -100f ${log_dir}/${node}.chain
}
function cita_consensus() {
    node=node$1
	tail -100f ${log_dir}/${node}.consensus
}

function cita_jsonrpc() {
    node=node$1
	tail -100f ${log_dir}/${node}.jsonrpc
}

function cita_network() {
    node=node$1
	tail -100f ${log_dir}/${node}.network
}

function cita_clean(){
    node=node$1
    rm -rf ${log_dir}
    rm -rf ${data_dir}

}

function cita_disk(){
    while :
    do
        echo
        echo
        echo "disk usage bytes $(du -s ./data)"
        sleep 3
    done
}

function cita_ram(){ 

    pid_1=$(tail -4 .pid| head -1)
    pid_2=$(tail -3 .pid| head -1)
    pid_3=$(tail -2 .pid| head -1)
    pid_4=$(tail -1 .pid)
    while :
    do
        mem_link=$(free | grep "Mem" | awk '{print $2}')
        mem_total=$[$mem_link*1024]
        echo "the total memory:$mem_total"
        vsize_1=$(cat /proc/$pid_1/stat | awk '{print $23}')   
        vsize_2=$(cat /proc/$pid_2/stat | awk '{print $23}') 
        vsize_3=$(cat /proc/$pid_3/stat | awk '{print $23}') 
        vsize_4=$(cat /proc/$pid_4/stat | awk '{print $23}')  
        rss_1=$(cat /proc/$pid_1/stat | awk '{print $24}')   
        rss_2=$(cat /proc/$pid_2/stat | awk '{print $24}') 
        rss_3=$(cat /proc/$pid_3/stat | awk '{print $24}') 
        rss_4=$(cat /proc/$pid_4/stat | awk '{print $24}')

        mem_node_total=$[vsize_1+vsize_2+vsize_3+vsize_4+rss_1+rss_2+rss_3+rss_4]
        mem_network=$[vsize_1+rss_1]
        mem_consensus_tende=$[vsize_2+rss_2]
        mem_jsonrpc=$[vsize_3+rss_3]
        mem_chain=$[vsize_4+rss_4]

        echo "the node memory:$mem_node_total"
        echo "the network memory:$mem_network"
        echo "the consensus_tende memory:$mem_consensus_tende"
        echo "the jsonrpc memory:$mem_jsonrpc"
        echo "the chain memory:$mem_chain"
        echo 
        sleep 3
    done
}

function cita_cpu(){
    pid_1=$(tail -4 .pid| head -1)
    pid_2=$(tail -3 .pid| head -1)
    pid_3=$(tail -2 .pid| head -1)
    pid_4=$(tail -1 .pid)
    top -b -p ${pid_1},${pid_2},${pid_3},${pid_4}|tee ${log_dir}/cpu.log
}

function cita_help(){
    echo
    echo "      usage:      cita command nodeid"
    echo
    echo "      command description:"
    echo
    echo "      setup            setup cita run environment(require sudo privilege)"
    echo
    echo "      start            start cita"
    echo
    echo "      stop             stop cita"
    echo
    echo "      restart          restart cita"
    echo
    echo "      status           display cita run status"
    echo
    echo "      jsonrpc          display cita's jsonrpc log information"
    echo
    echo "      chain            display cita's chain log information"
    echo
    echo "      consensus        display cita's consensus log information"
    echo
    echo "      network          display cita's network log information"
    echo
    echo "      clean            clean cita log file"
    echo
    echo "      version          display cita version"
    echo
    echo "      cpu              display cita's cpu information"
    echo
    echo "      ram              display cita's ram information"
    echo
    echo "      disk             display cita's disk information"
    echo
    echo "      help             display help information"
    echo
    echo
}

SCRIPT_PATH=$(cd `dirname $0`; pwd)

if [ $# -gt 3 ];
then
    cita_help
else
    pushd $SCRIPT_PATH > /dev/null
    case $1 in
        setup) cita_setup $2;;
        start) cita_start $2 $3;;
        stop) cita_stop $2;;
        restart) cita_restart $2;;
        status) cita_status $2;;
        jsonrpc) cita_jsonrpc $2;;
        chain) cita_chain $2;;
        consensus) cita_consensus $2;;
        clean) cita_clean $2;;
        network) cita_network $2;;
        version) echo "0.9";;
        cpu) cita_cpu $2;;
        ram) cita_ram $2;;
        disk) cita_disk $2;;
        help) cita_help ;;
        *) cita_help;;
    esac
    popd > /dev/null
fi
