[package]
name = "cita-crypto"
version = "0.1.0"
authors = ["lbqds <lbqds@cryptape.com>"]

[dependencies]
cita-ed25519 = { path = "../ed25519", optional = true }
cita-secp256k1 = { path = "../secp256k1", optional = true }
util = { path = "../util" }

[features]
default = ["secp256k1"]
ed25519 = ["cita-ed25519"]
secp256k1 = ["cita-secp256k1"]
