FROM ubuntu:16.04

RUN apt-get update -q                                                                                       \
    && apt-get install -y libstdc++6 libsodium18 rabbitmq-server libssl-dev libgoogle-perftools4 python-pip	\
    && rm -rf /var/lib/apt/lists

RUN pip install --user ethereum pysodium                                                                    \
    && rm -rf ~/.cache/pip

CMD /bin/bash
