# usage:
# git clone http://github.com/cryptape/cita
# cd cita
# docker run -v $PWD:/source cryptape/cita-build
FROM ubuntu:16.04

ENV PATH $PATH:/root/.cargo/bin
COPY *.sh /tmp/
RUN /tmp/install_develop.sh                     \
	&& rm -rf /var/lib/apt/lists                \
    && rm -rf ~/.cache/pip

WORKDIR /source
CMD /source/scripts/config_rabbitmq.sh          \
	&& make debug
